apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kube-downscaler-eviction-exclusions
spec:
  validationFailureAction: Enforce
  rules:
    - name: add-downscaler-exclude-annotation
      match:
        all:
        - resources:
            kinds:
              - Deployment
              - StatefulSet
              - autoscaling/v2/HorizontalPodAutoscaler
            namespaces:
              - mimir
              - loki
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              downscaler/exclude: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application.giantswarm.io/team: atlas
    rbac.kyverno.io/aggregate-to-background-controller: "true"
  name: kyverno:gs-o11y:kube-downscaler-eviction-exclusions
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - update
