apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: configure-pod-monitor-labelling-schema
  labels:
    [[ include "labels.common" . | nindent 4 ]]
spec:
  rules:
    - name: configure-pod-monitor-labelling-schema
      match:
        any:
        - resources:
            kinds:
            - monitoring.coreos.com/v1/PodMonitor
      mutate:
        foreach:
        - list: request.object.spec.podMetricsEndpoints
          patchesJson6902: |-
            - path: "/spec/podMetricsEndpoints/{{elementIndex}}/relabelings/-1"
              op: add
              value: {"sourceLabels": ["__meta_kubernetes_pod_label_app_kubernetes_io_name"], "targetLabel": "app"}
            - path: "/spec/podMetricsEndpoints/{{elementIndex}}/relabelings/-1"
              op: add
              value: {"sourceLabels": ["__meta_kubernetes_pod_node_name"], "targetLabel": "node"}
            - path: "/spec/podMetricsEndpoints/{{elementIndex}}/relabelings/-1"
              op: add
              value: {"sourceLabels": ["__meta_kubernetes_node_label_role"], "targetLabel": "role"}
