apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: configure-service-monitor-labelling-schema
spec:
  rules:
    - name: configure-service-monitor-labelling-schema
      match:
        resources:
          kinds:
          - monitoring.coreos.com/v1/ServiceMonitor
      mutate:
        patchStrategicMerge:
          spec:
            endpoints:
              - relabelings:
                  # Service Monitors are currently only supported on management clusters, so we can enforce the cluster_id and cluster_type.
                - replacement: "[[ .Values.managementCluster.name ]]"
                  targetLabel: cluster_id
                - replacement: "management_cluster"
                  targetLabel: cluster_type
                  # Since we only support management clusters, all resources are considered as highest service priority
                - replacement: "highest"
                  targetLabel: service_priority
                - replacement: "[[ .Values.provider.kind ]]"
                  targetLabel: provider
                - replacement: "[[ .Values.managementCluster.name ]]"
                  targetLabel: installation
                - sourceLabels: [__meta_kubernetes_namespace]
                  targetLabel: namespace
                  # If "app.kubernetes.io/instance" is used correctly eveywhere, it is a unique name identifying
                  # the instance of an application, so it is safe to use as the "app" label on the metrics
                - sourceLabels: [ __meta_kubernetes_pod_label_app_kubernetes_io_instance ]
                  targetLabel: app
                - sourceLabels: [__meta_kubernetes_pod_name]
                  targetLabel: pod
                - sourceLabels: [__meta_kubernetes_pod_container_name]
                  targetLabel: container
                - sourceLabels: [__meta_kubernetes_pod_node_name]
                  targetLabel: node
                - sourceLabels: [__meta_kubernetes_node_label_role]
                  targetLabel: role
                - replacement: "[[ .Values.managementCluster.customer ]]"
                  targetLabel: customer
                ## We get the organization from the namespace (org-organization_name)
                - replacement: "{{ request.namespace }}" 
                  targetLabel: organization
                ## Then we remove the org prefix
                - sourceLabels: [organization]
                  regex: org-(.*)
                  replacement: "${1}"
                  targetLabel: organization
